package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"
	"fmt"

	"github.com/Kitsuya0828/Next.js-gqlgen-app/docs/chapter03/graph/model"
	interanal "github.com/Kitsuya0828/Next.js-gqlgen-app/docs/chapter03/internal"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Mutation returns interanal.MutationResolver implementation.
func (r *Resolver) Mutation() interanal.MutationResolver { return &mutationResolver{r} }

// Query returns interanal.QueryResolver implementation.
func (r *Resolver) Query() interanal.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
